# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - fb/*
  paths:
    include:
    - src/yaml-demo-webapp/*
    - .azure/pipelines/webapp/*

variables:
  - group: YAML-Dev-Variables
  
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: 'BuildArtifact'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        projects: src\yaml-demo-webapp\sample-mvc.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    - publish: $(System.DefaultWorkingDirectory)/publish_output
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: 'DeployToTest'
    displayName: Deploy web app.
    pool:
      vmImage: 'ubuntu-latest'
    environment: Test
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: Azure Web App Deploy
            inputs:
              azureSubscription: $(Env-AzureSubscription)
              appName: $(Env-AzureWebAppName)
              package: $(Pipeline.Workspace)/drop/*.zip

