# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/infrastructure/*
    - .azure/pipelines/infrastructure/*

variables:
  - group: YAML-Dev-Variables

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: 'BuildArtifact'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '.azure/infrastructure/'
        Contents: '**'
        TargetFolder: 'iac'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'iac'
        artifact: 'drop'
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: 'DeployToTest'
    displayName: Deploy webapp infrastructure.
    pool:
      vmImage: 'ubuntu-latest'
    environment: Test
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: $(Env-AzureSubscription)
                action: 'Create Or Update Resource Group'
                resourceGroupName: '$(Env-ResourceGroupName)'
                location: '$(Env-AzureResourceLocation)'
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/drop/azuredeploy.json'
                overrideParameters: '-appServicePlanName $(Env-AzureAppServicePlanName) 
                                     -webAppName $(Env-AzureWebAppName)'
                deploymentMode: 'Incremental'
            